export async function validatePat(pat) {
  const response = await fetch('https://api.github.com/user', {
    headers: {
      Authorization: `Bearer ${pat}`,
      Accept: 'application/vnd.github.v3+json',
    },
  });

  if (!response.ok) {
    throw new Error('Invalid GitHub PAT');
  }

  const user = await response.json();
  return user.login;
}

export async function createRepo(pat, repoName) {
  const response = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${pat}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: repoName,
      description: 'Website generated by Web Prospector',
      public: true,
      auto_init: false,
    }),
  });

  if (!response.ok) {
    const err = await response.json();
    if (err.errors?.some((e) => e.message?.includes('name already exists'))) {
      throw new Error('REPO_EXISTS');
    }
    throw new Error(`Failed to create repo: ${err.message}`);
  }

  return await response.json();
}

export async function uploadFile(pat, owner, repo, filePath, content, message) {
  const encoded = btoa(unescape(encodeURIComponent(content)));

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message,
        content: encoded,
        branch: 'main',
      }),
    }
  );

  if (!response.ok) {
    const err = await response.json();
    throw new Error(`Failed to upload file: ${err.message}`);
  }

  return await response.json();
}

export async function enablePages(pat, owner, repo) {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pages`,
    {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        source: {
          branch: 'main',
          path: '/',
        },
      }),
    }
  );

  if (!response.ok) {
    const err = await response.json();
    throw new Error(`Failed to enable Pages: ${err.message}`);
  }

  return await response.json();
}

export async function getPagesStatus(pat, owner, repo) {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pages`,
    {
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: 'application/vnd.github.v3+json',
      },
    }
  );

  if (!response.ok) {
    return null;
  }

  return await response.json();
}

export async function waitForPages(pat, owner, repo, maxAttempts = 30) {
  for (let i = 0; i < maxAttempts; i++) {
    const status = await getPagesStatus(pat, owner, repo);
    if (status?.status === 'built' && status?.html_url) {
      return status.html_url;
    }
    await new Promise((resolve) => setTimeout(resolve, 3000));
  }
  // Return expected URL even if polling timed out
  return `https://${owner}.github.io/${repo}`;
}

export async function uploadBinaryFile(pat, owner, repo, filePath, base64Content, message) {
  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${pat}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message,
        content: base64Content,
        branch: 'main',
      }),
    }
  );

  if (!response.ok) {
    const err = await response.json();
    throw new Error(`Failed to upload file: ${err.message}`);
  }

  return await response.json();
}

/**
 * Downloads photos from the HTML, uploads them to the repo,
 * and returns the HTML with URLs replaced to relative paths.
 * Strips any remaining Google API keys from the HTML as a safety net.
 */
export async function processPhotosForPublish(pat, owner, repo, html) {
  // Match proxy photo URLs
  const photoRegex = /\/api\/google-places\/maps\/api\/place\/photo\?[^"'\s)]+/g;
  const matches = [...new Set(html.match(photoRegex) || [])];

  if (matches.length === 0) {
    return html;
  }

  const replacements = {};

  await Promise.all(
    matches.map(async (url, i) => {
      try {
        const response = await fetch(url);
        if (!response.ok) return;

        const blob = await response.blob();
        const buffer = await blob.arrayBuffer();
        const base64 = btoa(
          new Uint8Array(buffer).reduce((data, byte) => data + String.fromCharCode(byte), '')
        );

        const ext = blob.type === 'image/png' ? 'png' : 'jpg';
        const filePath = `images/photo-${i + 1}.${ext}`;

        await uploadBinaryFile(pat, owner, repo, filePath, base64, `Add photo ${i + 1}`);
        replacements[url] = filePath;
      } catch (err) {
        console.warn(`Failed to upload photo ${i + 1}:`, err);
      }
    })
  );

  // Replace all photo URLs with relative paths
  let processedHtml = html;
  for (const [originalUrl, relativePath] of Object.entries(replacements)) {
    processedHtml = processedHtml.replaceAll(originalUrl, relativePath);
  }

  return processedHtml;
}

export function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
